version: '3.8'
services:
  database:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - 2181:2181
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
    - 9092:9092
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=localhost
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper
  redisserver:
    image: redis:alpine
    ports:
    - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
    - node.name=elasticsearch
    - discovery.type=single-node
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - 9300:9300
    - 9200:9200
    networks:
      backend:
        aliases:
        - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9300
    ports:
    - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
    - ./config:/etc/logstash/conf.d
    ports:
    - 5000:5000
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
    - elasticsearch
    environment:
    - STORAGE_TYPE=elasticsearch
    - ES_HOSTS=elasticsearch:9300
    ports:
    - 9411:9411