version: '3.8'
services:
  database:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
        - database
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
    - 8071:8071
    environment:
      SPRING_PROFILES_ACTIVE: git
      ENCRYPT_KEY: secret-key
    networks:
      backend:
        aliases:
        - configserver
  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
    - 8070:8070
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
        - eurekaserver
  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
    - 8072:8072
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
        - gateway
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
    - 2181:2181
    networks:
      backend:
        aliases:
        - zookeeper
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
    - 9092:9092
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper
    networks:
      backend:
        aliases:
        - kafka
  redisserver:
    image: redis:alpine
    ports:
    - 6379:6379
    networks:
      backend:
        aliases:
        - redis
  authenticationservice:
    image: ostock/authentication-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
    - 8082:8082
    networks:
      backend:
        aliases:
        - authenticationservice
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      CONFIG_LOGBACK-DESTINATION: logstash:5000
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      authenticationservice:
        condition: service_started
      kafkaserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
    - 8080:8080
    networks:
    - backend
  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      CONFIG_LOGBACK-DESTINATION: logstash:5000
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      authenticationservice:
        condition: service_started
      kafkaserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
    - 8081:8081
    networks:
    - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
    - node.name=elasticsearch
    - discovery.type=single-node
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - 9300:9300
    - 9200:9200
    networks:
      backend:
        aliases:
        - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9300
    ports:
    - 5601:5601
    networks:
      backend:
        aliases:
        - kibana
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
    - ./config:/etc/logstash/conf.d
    ports:
    - 5000:5000
    networks:
      backend:
        aliases:
        - logstash
  zipkin:
    image: openzipkin/zipkin
    depends_on:
    - elasticsearch
    environment:
    - STORAGE_TYPE=elasticsearch
    - ES_HOSTS=elasticsearch:9300
    ports:
    - 9411:9411
    networks:
      backend:
        aliases:
        - zipkin
volumes:
  esdata1:
    driver: local
networks:
  backend:
    driver: bridge